import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'
// appearance={{ variables: {colorPrimary: '#36d399', colorBackground: "#030712", colorText: '#fafafa'}}}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider appearance={{
        baseTheme: dark,
        variables: {colorPrimary: '#36d399'},    
      }}>
          <NavBar />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
